services:
  jenkins-dind:
    build:
      context: test/jenkins-dind
      args:
        TAG: $TAG
    ports: 
      - "8080"
    volumes:
      - jpl-dind-cache:/var/lib/docker
      - ./:/opt/jpl-source
    privileged: true
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
  jenkins-agent1:
    image: "jenkins/jnlp-slave"
    entrypoint: ""
    command: 'bash -c "tail -f /var/log/*.log"'
    volumes:
      - ./:/opt/jpl-source
  jenkins-agent2:
    image: "jenkins/jnlp-slave"
    entrypoint: ""
    command: 'bash -c "tail -f /var/log/*.log"'
    volumes:
      - ./:/opt/jpl-source
volumes:
  jpl-dind-cache:
  jpl-jenkins-dind-home:
