version: '3.4'
services:
  jenkins-dind:
    image: "redpandaci/jenkins-dind"
    ports: 
      - "8080"
    volumes:
      - jpl-dind-cache:/var/lib/docker
      - ./:/tmp/jpl-source
    privileged: true
  jenkins-agent1:
    image: "jenkins/jnlp-slave"
    entrypoint: ""
    command: 'bash -c "tail -f /var/log/*.log"'
    volumes:
      - ./:/tmp/jpl-source
  jenkins-agent2:
    image: "jenkins/jnlp-slave"
    entrypoint: ""
    command: 'bash -c "tail -f /var/log/*.log"'
    volumes:
      - ./:/tmp/jpl-source
volumes:
  jpl-dind-cache:
